export const SECTION_TOPICS: Record<string, string[]> = {
  "Chem/Phys": [
    "Atomic Structure",
    "Periodic Trends",
    "Bonding & Intermolecular Forces",
    "Acids & Bases",
    "Electrochemistry",
    "Thermodynamics & Thermochemistry",
    "Kinetics & Equilibrium",
    "Solutions & Colligative Properties",
    "Nuclear Chemistry",
    "Kinematics & Dynamics",
    "Work, Energy & Power",
    "Fluids & Pressure",
    "Electricity & Magnetism",
    "Circuits",
    "Waves & Sound",
    "Optics & Light",
    "Functional Groups & Nomenclature",
    "Stereochemistry & Chirality",
    "Reaction Mechanisms",
    "Lab Techniques & Separations",
  ],
  "CARS": [
    "Passage Strategy & Mapping",
    "Main Idea & Central Argument",
    "Detail & Inference Questions",
    "Tone, Attitude & Author Purpose",
    "Strengthen, Weaken & Evaluate",
    "Vocabulary in Context",
  ],
  "Bio/Biochem": [
    "Amino Acids, Proteins & Enzymes",
    "Enzyme Kinetics & Inhibition",
    "Metabolism: Glycolysis & Fermentation",
    "Metabolism: TCA Cycle & Oxidative Phosphorylation",
    "Lipid Metabolism",
    "DNA & RNA Structure",
    "DNA Replication & Repair",
    "Transcription & RNA Processing",
    "Translation & Post-Translational Modification",
    "Gene Regulation & Epigenetics",
    "Recombinant DNA & Biotechnology",
    "Cell Structure & Organelles",
    "Cell Membrane & Transport",
    "Cell Signaling & Signal Transduction",
    "Cell Cycle & Mitosis",
    "Meiosis & Gametogenesis",
    "Mendelian Genetics & Heredity",
    "Chromosomal Inheritance",
    "Molecular Genetics & Mutations",
    "Population Genetics",
    "Nervous System & Neurophysiology",
    "Endocrine System",
    "Cardiovascular System",
    "Respiratory System",
    "Renal & Urinary System",
    "Digestive System & Nutrition",
    "Musculoskeletal System",
    "Immune System & Inflammation",
    "Reproductive System",
    "Microbiology (Bacteria, Viruses, Fungi)",
    "Evolution & Natural Selection",
  ],
  "Psych/Soc": [
    "Biological Bases of Behavior",
    "Sensation & Perception",
    "Learning & Conditioning",
    "Memory & Cognition",
    "Language & Thought",
    "Motivation, Emotion & Stress",
    "Developmental Psychology",
    "Personality Theories",
    "Psychological Disorders",
    "Treatment & Therapeutic Approaches",
    "Social Structure & Institutions",
    "Culture & Norms",
    "Socialization & Social Learning",
    "Social Stratification & Inequality",
    "Demographics & Social Change",
    "Social Behavior & Influence",
  ],
};
